### ISSUE TITLE
Diagrammes de séquence

### ISSUE THREAD

**Issue by akraxx** [rizomm-ramm/carpooling#18]

**Comment by Maraaa** [comment]
![gestion passagers sequence diagram](https://cloud.githubusercontent.com/assets/9623698/6768776/7a1e99f6-d07f-11e4-9414-8101c209edaa.png)
![gestion reservations inscription sequence diagram](https://cloud.githubusercontent.com/assets/9623698/6768775/7a1dc6e8-d07f-11e4-9f6d-866dbf543d2a.png)
![gestion reservations recherche sequence diagram](https://cloud.githubusercontent.com/assets/9623698/6768774/7a1db91e-d07f-11e4-8a36-23739b6b0d92.png)
![gestion reservations se retirer sequence diagram](https://cloud.githubusercontent.com/assets/9623698/6768779/7a2357d4-d07f-11e4-918f-f3de4cd0f749.png)
![inscription sequence diagram](https://cloud.githubusercontent.com/assets/9623698/6768777/7a20feb2-d07f-11e4-90e6-40c7f15ca986.png)
![sequence_connexion](https://cloud.githubusercontent.com/assets/9623698/6768778/7a22fb54-d07f-11e4-8641-30cac0004cc0.png)
![gestion abonnement modifier sequence diagram](https://cloud.githubusercontent.com/assets/9623698/6768780/7a2fa836-d07f-11e4-82db-f733c094b6cc.png)
![gestion abonnement payer sequence diagram](https://cloud.githubusercontent.com/assets/9623698/6768781/7a319682-d07f-11e4-9082-4560ccd9a52a.png)
![gestion abonnement resilier sequence diagram](https://cloud.githubusercontent.com/assets/9623698/6768782/7a3232cc-d07f-11e4-8afb-bad70449721a.png)
![gestion compte 1 sequence diagram](https://cloud.githubusercontent.com/assets/9623698/6768783/7a34d3d8-d07f-11e4-9ea6-c0c55a3e8cd9.png)
![gestion compte suppression sequence diagram](https://cloud.githubusercontent.com/assets/9623698/6768784/7a379cb2-d07f-11e4-93cc-fac75c3c9573.png)
![gestion conducteurs contacter sequence diagram](https://cloud.githubusercontent.com/assets/9623698/6768785/7a37bc6a-d07f-11e4-9311-47c80973d514.png)
![gestion conducteurs sequence diagram](https://cloud.githubusercontent.com/assets/9623698/6768786/7a408cdc-d07f-11e4-90fa-1368284ca697.png)
![gestion coordonnees bancaires sequence diagram](https://cloud.githubusercontent.com/assets/9623698/6768787/7a438482-d07f-11e4-8853-514879c25207.png)
![gestion itineraire modification sequence diagram](https://cloud.githubusercontent.com/assets/9623698/6768788/7a44b7b2-d07f-11e4-8df3-f223192a5016.png)
![gestion itineraire nouveau sequence diagram](https://cloud.githubusercontent.com/assets/9623698/6768789/7a4750a8-d07f-11e4-93fe-e30098e68a70.png)
![gestion itineraire suppression sequence diagram](https://cloud.githubusercontent.com/assets/9623698/6768791/7a4e6212-d07f-11e4-8e38-6dcc929dd2c5.png)
![gestion passagers contacter sequence diagram](https://cloud.githubusercontent.com/assets/9623698/6768790/7a4dee90-d07f-11e4-9a5f-6d2703a82c65.png)
